### Test sign call

@BASE_URL = http://localhost:8080/api/v1

# @name signDocument
POST {{BASE_URL}}/sign HTTP/1.1
content-type: application/json

{
    "claim": "{\"firstName\": \"First\", \"lastName\": \"Last\"}",
    "documentKey": "ticket"
}

### Test Job status call
@jobID = {{signDocument.response.body.jobID}}
# @name getJobStatus
GET {{BASE_URL}}/job/{{jobID}} HTTP/1.1


### Test verify

POST http://localhost:8080/api/v1/verify HTTP/1.1
content-type: application/json

{
    "signature": "eyJhbGciOiJFUzI1NiIsImtpZCI6InRlc3Qtc2lnbi1rZXkifQ.eyJmaXJzdE5hbWUiOiJGaXJzdCIsImxhc3ROYW1lIjoiTGFzdCJ9.TZoFkW1-qENnp5BYg2pYx1HVMMFZIuqzIy4Rx_kK0KeHLBJVwkJxN7iSJHDnLtaajle1w3XjoHMCxO6lPMQNvQ"
}
