apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  selector:
    app: server
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-signing
type: Opaque
data: 
  SIGN_PUBLIC_KEY: {{ .Files.Get "secrets/ec256-public.pem.base64" | b64enc }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: {{ .Release.Name }}-api
          image: {{ .Values.registry.url }}/certify-api
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: PORT
              value: "8080"
            - name: REDIS_HOST
              value: {{ .Release.Name }}-redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: redis-password
            - name: SIGN_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-signing
                  key: SIGN_PUBLIC_KEY
          imagePullPolicy: Always