apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
  labels:
    release: {{ .Release.Name }}
    deploymentTime: {{ now | date "20060102150405" | quote}}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    app: client-server
  ports:
    - port: 80
      targetPort: {{ .Values.client.port }}
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client
  labels:
    release: {{ .Release.Name }}
    deploymentTime: {{ now | date "20060102150405" | quote}}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        release: {{ .Release.Name }}
        deploymentTime: {{ now | date "20060102150405" | quote}}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: {{ .Release.Name }}-client
          image: {{ .Values.registry.url }}/certify-client
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: API_URL
              value: "http://localhost:{{ .Values.api.port }}/api/v1"
          imagePullPolicy: Always