apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-template-files
  labels:
    release: {{ .Release.Name | quote }}
data:
{{ (.Files.Glob "data/templates/*").AsConfig | indent 2 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-install"
  labels:
    release: "{{ .Release.Name }}"
    deploymentTime: {{ now | date "20060102150405" | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "3"
spec:
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        deploymentTime: {{ now | date "20060102150405" | quote }}
        release: {{ .Release.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: minio-post
    spec:
      restartPolicy: Never
      containers:
        - name: "{{ .Release.Name }}-post-install"
          image: "minio/mc:RELEASE.2022-12-13T00-23-28Z"
          command: ["/bin/sh", "-c", {{ .Files.Get "scripts/add_templates.sh" | quote }} ]
          env:
            - name: MINIO_HOST
              value: {{ .Release.Name }}-minio
            - name: MINIO_PORT
              value: {{ quote .Values.minio.minioAPIPort }}
            - name: MINIO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-minio
                  key: rootUser
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-minio
                  key: rootPassword
          volumeMounts:
          - name: template-files
            mountPath: /data/templates
      volumes:
      - name: template-files
        configMap:
          name: {{ .Release.Name }}-template-files