apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-signing
  labels:
    release: {{ .Release.Name }}
    deploymentTime: {{ now | date "20060102150405" | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data: 
  SIGN_PUBLIC_KEY: {{ .Files.Get "secrets/ec256-public.pem.base64" | b64enc }}
  SIGN_PRIVATE_KEY: {{ .Files.Get "secrets/ec256-key-pair.pem.base64" | b64enc }}