version: "3.3"

services: 
  certify-api:
    image: paul/certify-api
    ports: 
      - "8082:8082"
    environment:
      - PORT=8082
      - SIGN_PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFc05sQVdzZHhaWVUwZ2hYcGVWNVdWUUpobEk4dQpFdFdRSDF6NnFGZ3d5VmhUMjBOYWV3QklSbXFCMWlRbG1YUkkwQUdrZDZlYkxHRVdGWG5KYjQ5WHFBPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
    build: 
      context: ../api
      dockerfile: Dockerfile
    depends_on:
      - certify-renderer-1
      - certify-renderer-2
  certify-renderer-1:
    image: paul/certify-renderer
    build: 
      context: ../renderer
      dockerfile: Dockerfile
    environment:
      - SERVICE_ID=1
      - SIGN_PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFc05sQVdzZHhaWVUwZ2hYcGVWNVdWUUpobEk4dQpFdFdRSDF6NnFGZ3d5VmhUMjBOYWV3QklSbXFCMWlRbG1YUkkwQUdrZDZlYkxHRVdGWG5KYjQ5WHFBPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
      - SIGN_PRIVATE_KEY=LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdac1hsWUtDYVpBd0JyUm1NRk5qeVVBTXIzZnhGdlJ0L1BYRnJOazVqdWRvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFc05sQVdzZHhaWVUwZ2hYcGVWNVdWUUpobEk4dUV0V1FIMXo2cUZnd3lWaFQyME5hZXdCSQpSbXFCMWlRbG1YUkkwQUdrZDZlYkxHRVdGWG5KYjQ5WHFBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    depends_on:
      - redis
      - createbuckets
  certify-renderer-2:
    image: paul/certify-renderer
    build: 
      context: ../renderer
      dockerfile: Dockerfile
    environment:
      - SERVICE_ID=2
      - SIGN_PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFc05sQVdzZHhaWVUwZ2hYcGVWNVdWUUpobEk4dQpFdFdRSDF6NnFGZ3d5VmhUMjBOYWV3QklSbXFCMWlRbG1YUkkwQUdrZDZlYkxHRVdGWG5KYjQ5WHFBPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
      - SIGN_PRIVATE_KEY=LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdac1hsWUtDYVpBd0JyUm1NRk5qeVVBTXIzZnhGdlJ0L1BYRnJOazVqdWRvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFc05sQVdzZHhaWVUwZ2hYcGVWNVdWUUpobEk4dUV0V1FIMXo2cUZnd3lWaFQyME5hZXdCSQpSbXFCMWlRbG1YUkkwQUdrZDZlYkxHRVdGWG5KYjQ5WHFBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    depends_on:
      - redis
      - createbuckets
  redis:
    image: "redis/redis-stack:6.2.4-v3"
    ports: 
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--requirepass sOmE_sEcUrE_pAsS
    volumes:
      - ./redis-conf/redis.conf:/redis-stack.conf
  minio:
    image: minio/minio:RELEASE.2022-11-08T05-27-07Z
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./template.html:/template.html
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/results;
      /usr/bin/mc mb myminio/templates;
      /usr/bin/mc od if=/template.html of=myminio/templates/ticket;
      /usr/bin/mc anonymous set download myminio/results;
      exit 0;
      "
  client:
    image: nginx:1.23.2-alpine
    ports:
      - "8081:80"
    environment:
      - API_URL=http://localhost:8082/api/v1
    volumes:
      - ../client/public:/usr/share/nginx/html:ro
      - ../client/entrypoint/add_env.sh:/docker-entrypoint.d/add_env.sh