version: "3.8"

services: 
  certify-api:
    image: paul/certify-api
    ports: 
      - "8080:8080"
    build: 
      context: ../api
      dockerfile: Dockerfile
    depends_on:
      - redis
  certify-renderer-1:
    image: paul/certify-renderer
    build: 
      context: ../renderer
      dockerfile: Dockerfile
    environment:
      - SERVICE_ID=1
    depends_on:
      - redis
  certify-renderer-2:
    image: paul/certify-renderer
    build: 
      context: ../renderer
      dockerfile: Dockerfile
    environment:
      - SERVICE_ID=2
    depends_on:
      - redis
  redis:
    image: "redis/redis-stack:6.2.4-v3"
    ports: 
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--requirepass sOmE_sEcUrE_pAsS
    volumes:
      - ./redis-conf/redis.conf:/redis-stack.conf