version: "3.8"

services: 
  certify-api:
    image: paul/certify-api
    ports: 
      - "8080:8080"
    build: 
      context: ../api
      dockerfile: Dockerfile
    depends_on:
      - redis
  certify-renderer:
    image: paul/certify-renderer
    build: 
      context: ../renderer
      dockerfile: Dockerfile
    depends_on:
      - redis
  redis:
    image: "redis:7-alpine"
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass sOmE_sEcUrE_pAsS
    ports: 
      - "6379:6379"
    volumes:
      - ./redis-conf/redis.conf:/usr/local/etc/redis/redis.conf