version: "3.8"

services: 
  certify-api:
    image: paul/certify-api
    ports: 
      - "8080:8080"
    secrets:
      - SIGN_PUBLIC_KEY
    build: 
      context: ../api
      dockerfile: Dockerfile
    depends_on:
      - certify-renderer-1
      - certify-renderer-2
  certify-renderer-1:
    image: paul/certify-renderer
    build: 
      context: ../renderer
      dockerfile: Dockerfile
    environment:
      - SERVICE_ID=1
    secrets:
      - SIGN_PRIVATE_KEY
    depends_on:
      - redis
      - createbuckets
  certify-renderer-2:
    image: paul/certify-renderer
    build: 
      context: ../renderer
      dockerfile: Dockerfile
    environment:
      - SERVICE_ID=2
    secrets:
      - SIGN_PRIVATE_KEY
    depends_on:
      - redis
      - createbuckets
  redis:
    image: "redis/redis-stack:6.2.4-v3"
    ports: 
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--requirepass sOmE_sEcUrE_pAsS
    volumes:
      - ./redis-conf/redis.conf:/redis-stack.conf
  minio:
    image: minio/minio:RELEASE.2022-11-08T05-27-07Z
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./template.html:/template.html
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/results;
      /usr/bin/mc mb myminio/templates;
      /usr/bin/mc od if=/template.html of=myminio/templates/ticket;
      exit 0;
      "
  client:
    image: nginx:1.23.2-alpine
    ports:
      - "8081:80"
    volumes:
      - ../client:/usr/share/nginx/html:ro
secrets:
  SIGN_PRIVATE_KEY:
    file: ./secrets/ec256-key-pair.pem
  SIGN_PUBLIC_KEY:
    file: ./secrets/ec256-public.pem