# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry:
  url: localhost:32000

redis: 
  architecture: standalone

minio:
  mode: standalone
  minioAPIPort: "9000"
  minioConsolePort: "9001"
  ## AccessKey and secretKey is generated when not set
  rootUser: ""
  rootPassword: ""
  replicas: 1
  buckets:
    - name: results
      policy: download
      purge: false 
    - name: templates
      policy: download
      purge: false 

api:
  port: "8080"

client:
  port: "8084"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}